### ISSUE TITLE
Error: Invalid header: Does not start with Cr24 

### ISSUE THREAD

**Issue by thedoublejay** [MarshallOfSound/electron-devtools-installer#165]
### Issue Details

* **Electron Version:**
  * 11.2.0
* **Operating System:**
  * Windows 20H2
* **Last Known Working Electron version:**
  * 11.1.1

### Expected Behavior
Using the latest Electron 11.2.0 build, with `electron-devtools-installer 3.1.1`, the app should build successfully.

### Actual Behavior
Using the latest Electron 11.2.0 build, with `electron-devtools-installer 3.1.1`, the build fails. There's an error `Error: Invalid header: Does not start with Cr24` when running the build. Previously using Electron 11.1.1, this error is also displayed but the build still works. It breaks with Redux Dev Tools and React Dev Tools.

### Screenshots
![image](https://user-images.githubusercontent.com/25013382/104402201-bb3e3580-5590-11eb-9eee-d32314bceffe.png)

**Comment by GiovaniBiagi** [comment]
having the same issue, any workaround ?

**Comment by BlackHole1** [comment]
I submitted a fixed PR for this issue and I am now waiting for the merge:

https://github.com/MarshallOfSound/electron-devtools-installer/pull/177

**Comment by BlackHole1** [comment]
But there are some errors in your picture. This PR may not have been fixed yet. Can you tell me which plugins are installed that caused the error?

eg: `Permission 'notifications' is unknown or URL pattern is malformed.`

**Comment by Zyles** [comment]
> @thedoublejay @GiovaniBiagi I submitted a fixed PR for this issue and I am now waiting for the merge: #177
> 
> This method can be used to temporarily solve this problem:
> 
> ```shell
> yarn add electron-devtools-installer@git://github.com/BlackHole1/electron-devtools-installer#d2aef8692a6b3d797ec1aa9b1b24092e7461fb63 -D
> ```

Does not work for me. Still unable to compile.
`Uncaught (in promise) Error: Invalid header: Does not start with Cr24`

```
  "dependencies": {
    "@keyv/sqlite": "^2.0.2",
    "@mapbox/node-pre-gyp": "^1.0.0",
    "axios": "^0.21.1",
    "axios-cache-adapter": "^2.7.0",
    "axios-retry-interceptor": "^1.1.0",
    "cachios": "^2.2.5",
    "core-js": "^3.9.0",
    "electron-oauth-helper": "^5.0.1",
    "electron-store": "^7.0.2",
    "keyv": "^4.0.3",
    "lodash": "^4.17.21",
    "material-design-icons-iconfont": "^5.0.1",
    "moment": "^2.29.1",
    "node-fetch": "^2.6.0",
    "numeral": "^2.0.6",
    "retry-axios": "^2.4.0",
    "sqlite": "^4.0.19",
    "sqlite3": "5.0.0",
    "uniqid": "^5.3.0",
    "validate.js": "^0.13.1",
    "vue": "^2.6.12",
    "vue-router": "^3.5.1",
    "vuetify": "^2.4.4",
    "vuex": "^3.6.2",
    "vuex-electron": "^1.0.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.12.17",
    "@babel/core": "^7.12.17",
    "@babel/eslint-parser": "^7.12.17",
    "@babel/node": "^7.12.17",
    "@babel/plugin-proposal-optional-chaining": "^7.12.17",
    "@vue/cli-plugin-babel": "^3.12.1",
    "@vue/cli-plugin-eslint": "^3.12.1",
    "@vue/cli-service": "^3.12.1",
    "electron": "^11.3.0",
    "electron-builder": "^22.9.1",
    "electron-devtools-installer": "git://github.com/BlackHole1/electron-devtools-installer.git#d2aef8692a6b3d797ec1aa9b1b24092e7461fb63",
    "eslint": "^7.20.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-html": "^6.1.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-vue": "^7.6.0",
    "sass": "^1.32.8",
    "sass-loader": "^10.1.1",
    "vue-cli-plugin-electron-builder": "^1.4.6",
    "vue-cli-plugin-vuetify": "^0.6.3",
    "vue-template-compiler": "^2.6.12",
    "vuetify-loader": "^1.7.2"
  }
```

**Comment by vedmant** [comment]
Having the same issue, what's the fix?

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.

**Comment by jdsika** [comment]
I am note sure where it is coming from but I happen to get this error when trying to run Lichtblick [here](https://github.com/Lichtblick-Suite/lichtblick/issues/330)  on a Ubuntu 24.04 with `"electron": "33.2.1",` as project dependency.
